### ISSUE TITLE
create docker compose file for the project

### ISSUE THREAD

**Issue by keertirajmalik** [keertirajmalik/expenser#24]
```yaml
services:
  db:
    image: postgres
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    secrets:
      - db-password
    environment:
      - POSTGRES_DB=app
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  letsencrypt:

secrets:
  db-password:
    external: true
```
